# Question1

In [10]:
import pandas as pd

In [11]:
print(pd.__version__)

2.0.3


In [6]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-16 21:27:42--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv’

housing.csv         100%[===================>]   1.36M   381KB/s    in 3.7s    

2023-09-16 21:27:47 (381 KB/s) - ‘housing.csv’ saved [1423529/1423529]



In [79]:
df = pd.read_csv('housing.csv')

# Question2

In [80]:
df.shape

(20640, 10)

# Question3

In [81]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

# Question4

In [82]:
df['ocean_proximity'].nunique()

5

# Question5

In [83]:
df[df['ocean_proximity']=='NEAR BAY'].median_house_value.mean()

259212.31179039303

# Question6

In [84]:
df['total_bedrooms'].mean()

537.8705525375618

In [85]:
df['total_bedrooms']=df['total_bedrooms'].fillna(df['total_bedrooms'].mean())

In [86]:
df['total_bedrooms'].mean()

537.8705525375617

# Question 7

In [87]:
import numpy as np

In [88]:
filtered_df=df[df['ocean_proximity']=='ISLAND']
selected_columns=filtered_df[['housing_median_age','total_rooms','total_bedrooms']]

In [89]:
selected_columns

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [90]:
X=np.array(selected_columns)
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [91]:
X.T

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [92]:
XTX=X.T.dot(X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [93]:
XTX_inv=np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [94]:
y=np.array([950, 1300, 800, 1000, 1300])

In [95]:
w=XTX_inv.dot(X.T).dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])